name: Continuous integration with github
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SetupJDK11
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
        - name: clean project
          run: ./gradlew clean
        - name: run all test
          run: ./gradlew testClasses
        - name: create .jar and install
          run: ./gradlew bootJar
